stages:
  - test
  - publish

node_10:
  stage: test
  image: node:10.9.0-alpine
  before_script:
    - npm ci
  script:
    - npm test
  only:
    - tags

npm:
  stage: publish
  image: node:10.9.0-alpine
  before_script:
    - npm ci
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
  script:
    - npm publish
  only:
    - tags
